name: Backend CI & Coverage

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'src/**'
      - 'prisma/**'
      - 'package.json'
      - 'package-lock.json'
      - 'jest.config.js'
  pull_request:
    branches: [ main, develop ]
    paths:
      - '**/*.ts'
      - 'prisma/**'

env:
  NODE_VERSION: 18

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: bookverse_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install deps
        run: npm ci

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Run Tests with Coverage
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/bookverse_test
          JWT_SECRET: test-secret
        run: npm run test:coverage

      - name: Upload Coverage Artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: coverage
